{
  "branches": ["master"],
  
  "plugins": [
    # https://github.com/semantic-release/commit-analyzer     
    ["@semantic-release/commit-analyzer", {
      "preset": "conventionalcommits"
    }],
    
    "@semantic-release/release-notes-generator",
    ["@semantic-release/git", {
      "assets": ["CHANGELOG.md"]
    }],
    ["@semantic-release/changelog", {
      "changelogFile": "CHANGELOG.md"
    }],
    ["@semantic-release/github", {
      "assets": ["CHANGELOG.md", "dist/**"],
      "message": "chore(release): set `package.json` to ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}"
    }] 
  ]
}
