# Ref:
# - https://github.com/semantic-release/semantic-release
# - https://semantic-release.gitbook.io/semantic-release/extending/plugins-list

branches: ["master", {name: "develop", prerelease: true}]
preset: "conventionalcommits"
tagFormat: "v${version}"

plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/changelog"
  - "@semantic-release/git"
  - "@semantic-release/github"

# Verify all the conditions to proceed with the release.
verifyConditions:
  # Verify the presence and the validity of the Git authentication and release configuration
  - '@semantic-release/git'
  # Verify the presence and the validity of the GitHub authentication and release configuration
  - "@semantic-release/github"

# 1. Obtain the commit corresponding to the last release by analyzing Git tags
# 2. Determine the type of release based on the commits added since the last release.
analyzeCommits:
  - path: "@semantic-release/commit-analyzer"

# Verify the release conformity.
#verifyRelease:
#  - path: ""

# Generate release notes for the commits added since the last release
generateNotes:
  - path: "@semantic-release/release-notes-generator"
    writerOpts:
      groupBy: "type"
      commitGroupsSort:
        - "feat"
        - "perf"
        - "fix"
      commitsSort: "header"

# 1. Create a Git tag corresponding to the new release version
# 2. Prepare the release
prepare:
  # Create or update the changelog file in the local project repository
  - path: "@semantic-release/changelog"
    changelogFile: "CHANGELOG.md"
  # Push a release commit and tag, including configurable files
  - path: "@semantic-release/git"
    asset: ["CHANGELOG.md"]

# Publish the release
publish:
  - path: "@semantic-release/github"
    assets: [{path: "CHANGELOG.md", label: "changelog"}, "dist/**"}]
    message: "chore(release): set `package.json` to ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}"

# Notify of new releases or errors.
success:
  - "@semantic-release/github"
fail:
  - "@semantic-release/github"
