{
  "branches": ["master"],
  
  "plugins": [
    "@semantic-release/commit-analyzer",  
    "@semantic-release/release-notes-generator",
    "@semantic-release/git",
    ["@semantic-release/changelog", {
      "changelogFile": "CHANGELOG.md",
      "changelogTitle": "Title"
    }],
    ["@semantic-release/github", {
      "assets": ["CHANGELOG.md", "dist/**"],
      "message": "chore(release): set `package.json` to ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}"
    }] 
  ]
}
