name: Conventional Commit
on:
  pull_request:
    branches:
      - develop
      - master
    types: [opened, synchronize, reopened, edited]
    
  workflow_dispatch:
    
jobs:
  check:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.1.0
        with:
          node-version: 'lts/*'
      
      # semantic-release: it comes pre-installed in GitHub actions by default
      - name: Install semantic-release extra plugins
        run: |
              npm install --save-dev \
                semantic-release \
                @semantic-release/commit-analyzer \
                @semantic-release/changelog \
                @semantic-release/git \
                @semantic-release/release-notes-generator \
                conventional-changelog-conventionalcommits \
                @commitlint/cli \
                @commitlint/config-conventional
          
      - name: Validate all commits from PR
        run: |
          echo "module.exports = {extends: ['@commitlint/config-conventional']}" > commitlint.config.js
          npx commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --verbose

