name: Custom Dry-Run Release

# Controls when the workflow will run
on:
  repository_dispatch:
    types: [semantic-release]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  release-dryrun:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.1.0
        with:
          node-version: 'lts/*'
        
      - name: Install dependencies
        run: npx ci

      - name: Create minimal release.config.js
        run: |
          cat /dev/null > release.config.js
          echo <<EOF >> release.config.js \
          module.exports = { \
            'branches': [ \
              'master', \
            'preset': 'conventionalcommits', \
            'tagFormat': 'v${version}', \
            'plugins': [ \
              '@semantic-release/commit-analyzer', \
              ['@semantic-release/release-notes-generator', { \
                  preset: 'conventionalcommits', \
                  "writerOpts": { \
                    "commitsSort": ["perf", "feat", "fix"], \
                  } \
                } \
              ], \
              ["@semantic-release/exec", { \
                  "verifyReleaseCmd": "echo ${nextRelease.version} > .VERSION" \
                } \
              ], \
            ] \
          } \
          EOF
       
      # semantic-release: it comes pre-installed in GitHub actions by default
      - name: Install semantic-release extra plugins
        run: |
              npm install --save-dev \
                semantic-release \
                @semantic-release/commit-analyzer \
                @semantic-release/release-notes-generator \
                @semantic-release/exec \
                conventional-changelog-conventionalcommits
      - name: Dry-Run
        id: dry-run
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npx semantic-release --dry-run --no-ci
          echo "::set-output name=nextversion::$(cat .VERSION)"
      
      - name: Version
        run: |
          echo "Next version: ${{ steps.dry-run.outputs.nextversion }}"
          
