name: Full Release

# Controls when the workflow will run
on:
  repository_dispatch:
    types: [semantic-release]
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v3.0.2
        with:
          token: ${{ secrets.SEMANTICRELEASE }}
          fetch-depth: '0'
      
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.3.0
        with:
          node-version: 'lts/*'
        
      #- name: Install dependencies
      #  run: npx ci
       
      # semantic-release: it comes pre-installed in GitHub actions by default
      - name: Install semantic-release extra plugins
        run: |
              npm install --save-dev \
                semantic-release \
                @semantic-release/commit-analyzer \
                @semantic-release/changelog \
                @semantic-release/git \
                @semantic-release/release-notes-generator \
                @semantic-release/exec \
                conventional-changelog-conventionalcommits
      
      - name: Prepare script
        run: |
          chmod +x prepare-release.sh
      
      - name: Release
        id: release
        env:
          GITHUB_TOKEN: ${{ secrets.SEMANTICRELEASE }}
        run: |
          npx semantic-release
          echo "::set-output name=nextversion::$(cat .VERSION)"
          
      - name: Happy ending
        run: |
          if [[ ! -z "${{ steps.release.outputs.nextversion }}" ]]; then
            echo "✅ Release ${{ steps.release.outputs.nextversion }} created!" >> $GITHUB_STEP_SUMMARY
          else
            echo "❌ No relevant changes, no new version is released!" >> $GITHUB_STEP_SUMMARY
          fi

